server {
    listen 80;
    server_name localhost;
    
    # Root donde se encuentran los archivos de la aplicación
    root /usr/share/nginx/html;

    # Habilita compresión Gzip (opcional, pero buena práctica)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Intenta servir el archivo tal como está, si no existe,
        # redirige a index.html (necesario para el enrutamiento de React)
        try_files $uri $uri/ /index.html;
    }

    # Deshabilita el caché para index.html (para asegurar que siempre se obtenga la última versión)
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}